keys:
  - &admin_jan 35135CE577AD711F38259A99366572BE7D6C78A2
  - &server_vpsDev age1wv4uny737yrw264eegdpmhhffkm34d0v6677fwn4hstgallr339sm0a9rc
creation_rules:
  - path_regex: secrets/[^/]+$
    key_groups:
    - pgp:
      - *admin_jan
      age:
      - *server_vpsDev
  - path_regex: tunnel/[^/]+\.conf$
    key_groups:
    - pgp:
      - *admin_jan
      age:
      - *server_vpsDev
